# Origin: https://github.com/confluentinc/confluent-kafka-dotnet

language: csharp
sudo: required
dist: trusty

os:
   - linux
#   - osx  - osx is currently broken on travis

env:
    - PATH

install:
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libunwind8; fi
   - wget https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh
   - sudo bash dotnet-install.sh --version latest
   - export PATH=$HOME/.dotnet:$PATH
   - dotnet restore

script:
   - make build
   - dotnet pack ./src/Confluent.Kafka
   - make test
